/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package extendedui.swig;

public class EffekseerBackendCore {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;

    public EffekseerBackendCore() {
        this(EffekseerCoreJNI.new_EffekseerBackendCore(), true);
    }

    protected EffekseerBackendCore(long cPtr, boolean cMemoryOwn) {
        swigCMemOwn = cMemoryOwn;
        swigCPtr = cPtr;
    }

    public static EffekseerCoreDeviceType GetDevice() {
        return EffekseerCoreDeviceType.swigToEnum(EffekseerCoreJNI.EffekseerBackendCore_GetDevice());
    }

    public static boolean InitializeWithOpenGL() {
        return EffekseerCoreJNI.EffekseerBackendCore_InitializeWithOpenGL();
    }

    public static void Terminate() {
        EffekseerCoreJNI.EffekseerBackendCore_Terminate();
    }

    protected static long getCPtr(EffekseerBackendCore obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

    public synchronized void delete() {
        if (swigCPtr != 0) {
            if (swigCMemOwn) {
                swigCMemOwn = false;
                EffekseerCoreJNI.delete_EffekseerBackendCore(swigCPtr);
            }
            swigCPtr = 0;
        }
    }

    @SuppressWarnings("deprecation")
    protected void finalize() {
        delete();
    }

}
